# Generated by Django 4.2.2 on 2023-06-20 13:17

from django.db import migrations
import localflavor.in_.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='state',
            field=localflavor.in_.models.INStateField(default='DL', max_length=2),
        ),
    ]
