BRANDS= (
    ('bmw', 'BMW'),
    ('mercedes benz', 'Mercedes Benz'),
    ('audi', 'Audi'),
    ('subaru', 'Subaru'),
    ('tesla', 'Tesla'),
    ('jaguar', 'Jaguar'),
    ('land rover', 'Land Rover'),
    ('bentley', 'Bentley'),
    ('mazda','Mazda'),
    ('bugatti', 'Bugatti'),
    ('midual','Midual'),
    ('peugeot scooters','Peugeot Scooters'),
    ('ather energy','Ather Energy'),
    ('ultraviolette automotive','Ultraviolette Automotive'),
    ('aprilia','Aprilia'),
    ('piaggio','Piaggio'),
    ('ducati','Ducati'),
    ('suzuki','Suzuki'),
    ('yamaha','Yamaha'),
    ('kawasaki','Kawasaki'),
    ('ferrari', 'Ferrari'),
    ('lamborghini', 'Lamborghini'),
    ('honda', 'Honda'),
    ('toyota', 'Toyota'),
    ('chevrolet', 'Chevrolet'),
    ('porsche', 'Porsche'),
    ('tata','Tata'),
    ('mahindra','Mahindra'),
    ('hindustan motors','Hindustan Motors'),
    ('volkswagen','Volkswagen'),
    ('toyota','Toyota'),
    ('ford motor','Ford Motor'),
    ('tvs motors','TVS Motors'),
    ('ola electric','Ola Electric'),
    ('royal enfield','Royal Enfield'),
    ('hero motocorp','Hero Motocorp'),
    ('bajaj auto','Bajaj Auto'),
    
)

TRANSMISSION_OPTIONS = (
    ('automatic', 'Automatic'),
    ('manual', 'Manual'),
)