# Generated by Django 4.2.2 on 2023-07-01 07:30

from django.db import migrations, models
import django.db.models.deletion
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_photo'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='brand',
            field=models.CharField(choices=[('bmw', 'BMW'), ('mercedes benz', 'Mercedes Benz'), ('audi', 'Audi'), ('subaru', 'Subaru'), ('tesla', 'Tesla'), ('jaguar', 'Jaguar'), ('land rover', 'Land Rover'), ('bentley', 'Bentley'), ('bugatti', 'Bugatti'), ('midual', 'Midual'), ('peugeot scooters', 'Peugeot Scooters'), ('ather energy', 'Ather Energy'), ('ultraviolette automotive', 'Ultraviolette Automotive'), ('aprilia', 'Aprilia'), ('piaggio', 'Piaggio'), ('ducati', 'Ducati'), ('suzuki', 'Suzuki'), ('yamaha', 'Yamaha'), ('kawasaki', 'Kawasaki'), ('ferrari', 'Ferrari'), ('lamborghini', 'Lamborghini'), ('honda', 'Honda'), ('toyota', 'Toyota'), ('chevrolet', 'Chevrolet'), ('porsche', 'Porsche'), ('tata', 'Tata'), ('mahindra', 'Mahindra'), ('hindustan motors', 'Hindustan Motors'), ('volkswagen', 'Volkswagen'), ('toyota', 'Toyota'), ('ford motor', 'Ford Motor'), ('tvs motors', 'TVS Motors'), ('ola electric', 'Ola Electric'), ('royal enfield', 'Royal Enfield'), ('hero motocorp', 'Hero Motocorp'), ('bajaj auto', 'Bajaj Auto')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='color',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='engine',
            field=models.CharField(default='', max_length=24),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='', upload_to=main.utils.user_listing_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location'),
        ),
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='model',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='transmisson',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default=None, max_length=24),
        ),
        migrations.AddField(
            model_name='listing',
            name='vin',
            field=models.CharField(default='', max_length=17),
            preserve_default=False,
        ),
    ]
